### ISSUE TITLE
游戏更新兼容问题

### ISSUE THREAD

**Issue by batvbs** [makuwa8992/DSP_Mods#1]
严重程度：低，不影响功能
V0.10.30.22292版本更新中，戴森球对传送带进行了修改，现在可以按左右箭头倾斜传送带了（如图所示）
安装此mod后，修改将不会生效，【铺设时】依然是旧版传送带
![02fbfa1be44f2ebc756a15a950234cae](https://github.com/makuwa8992/DSP_Mods/assets/60730393/4490a326-24f1-4045-93ec-59326304833b)

**Comment by makuwa8992** [comment]
好的，等我有空看看改改

**Comment by makuwa8992** [comment]
已修复
